name: RedBeat CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Tests (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest] #, windows-latest] tests fail on windows
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run unittests
        run: make unittests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run flake8
        run: make lint
